version: '3'
# This example runs three servers, PostgreSQL, pgAdmin, and a frontEnd server

# Each service runs in a seperate container
services:
  flashcards-db:
    container_name: flashcards-db
    image: postgres:latest
    restart: always
    environment:
      DATABASE_HOST: flascards-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_DB: flashcards
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdatasource:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: amoramas1984@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - flashcards-db

volumes:
  pgdatasource:
  pgadmin-data:


networks:
  default:
